server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: api-gateway

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /book-service/v3/api-docs
        name: Book Service API
      - url: /cambio-service/v3/api-docs
        name: Cambio Service API

management:
  tracing:
    sampling:
      probability: 1.0