server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true

resilience4j:
  ratelimiter:
    instances:
      foo-bar:
        limit-for-period: 2
        limit-refresh-period: 15s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
  circuitbreaker:
    instances:
      foo-bar:
        sliding-window-size: 3
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 50s

spring:
  application:
    name: book-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    schemas: book_service
    user: root
    password: root

springdoc:
  api-docs:
    path: book-service/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0