spring:
  application:
    name: greeting-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

server:
  port: 8080

# allowing information: http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

# custom properties
greeting-service:
  greeting: "Hello"
  default-value: "World"


