spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Edvan-Oliveira/remote-config
          default-label: main # branch
          search-paths: greeting-service*
          #username: ...
          #password: ...

server:
  port: 8888


